apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: wildfly-s2i-pipeline-run
spec:
  serviceAccountName: wildfly-tekton-service-account
  pipelineRef:
    name: wildfly-s2i-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: wildfly-source-pvc
  params:
   - name: application-image
     value: quay.io/jmesnil/wildfly-tekton-app
   - name: source-url
     value: https://github.com/wildfly/quickstart.git
   - name: source-ref
     value: "23.0.2.Final"
   - name: source-context-dir
     value: microprofile-config
   - name: galleon-layers
     value: jaxrs-server,microprofile-platform
